version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: hasura
    volumes:
    - /opt/powix/db/:/var/lib/postgresql/data
  auth-server:
    build:
      context: ../
      dockerfile: ./packages/hasura-auth-server/Dockerfile
    environment:
      NODE_ENV: production
      PRIVATE_KEY: ${SIGNER_PRIVATE_KEY}
      HOST: 0.0.0.0
      PORT: 3000
    ports:
    - '3000'
    
  graphql-engine:
    image: hasura/graphql-engine:v2.22.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/hasura
      PG_DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
    command: /bin/sh -c 'if [ "$DEVELOPMENT_MODE" = "dev" ]; then export HASURA_GRAPHQL_DEV_MODE=true; fi && graphql-engine serve'
